# Generated by Django 3.0.7 on 2020-07-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20200702_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsdb',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
