# Generated by Django 3.0.7 on 2020-07-05 07:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200329_2240'),
        ('comments', '0003_commentsdb_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentsdb',
            old_name='active',
            new_name='approved_comment',
        ),
        migrations.AlterField(
            model_name='commentsdb',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='commentsdb',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.ProductDb'),
        ),
    ]
