# Generated by Django 3.0.7 on 2020-07-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20200705_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsdb',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
