# Generated by Django 3.0.7 on 2020-08-10 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('categories', models.CharField(max_length=255)),
                ('image', models.URLField(max_length=255)),
                ('nutriscore', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=255)),
                ('fat', models.FloatField()),
                ('saturated_fat', models.FloatField()),
                ('sugar', models.FloatField()),
                ('salt', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPersonalDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_product', to='products.ProductDb')),
                ('replaced_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replaced_product', to='products.ProductDb')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
