# Generated by Django 3.0.7 on 2020-08-10 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonaldb',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='userpersonaldb',
            constraint=models.UniqueConstraint(fields=('original_product', 'replaced_product', 'user'), name='no_double'),
        ),
    ]
