# Generated by Django 3.0.7 on 2020-08-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200810_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='categories',
            field=models.TextField(),
        ),
    ]
