# Generated by Django 3.0.7 on 2020-08-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200810_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydb',
            name='product_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='categorydb',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='categorydb',
            name='url',
            field=models.URLField(max_length=500),
        ),
        migrations.RemoveField(
            model_name='productdb',
            name='categories',
        ),
        migrations.AddField(
            model_name='productdb',
            name='categories',
            field=models.ManyToManyField(blank=True, to='products.CategoryDb'),
        ),
    ]
